name: osrm_dart_sdk
version: 0.0.1
description: Dart SDK for the Open Source Routing Machine
authors:
  - WBT-Solutions <development@wbt-solutions.de>
homepage: https://github.com/wbt-solutions/osrm_dart_sdk
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
  intl: ^0.16.1
  meta: ^1.1.8
dev_dependencies:
  test: ^1.3.0
